-- =========================
-- Core lookup tables
-- =========================

CREATE TABLE cohort (
    cohort_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_name      VARCHAR(255) NOT NULL
);

CREATE TABLE category (
    category_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name    VARCHAR(255) NOT NULL
);

CREATE TABLE season (
    season_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_name      VARCHAR(255) NOT NULL
);

CREATE TABLE application_method (
    application_method_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_method_name TEXT NOT NULL
);

CREATE TABLE fertilizer_type (
    fertilizer_type_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fertilizer_type_name VARCHAR(255) NOT NULL
);

CREATE TABLE usage (
    usage_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usage_name    TEXT NOT NULL
);

CREATE TABLE reason_not_sold (
    reason_not_sold_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason_not_sold_name TEXT NOT NULL
);

-- =========================
-- Actor tables
-- =========================

CREATE TABLE focal_point (
    focal_point_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    focal_point_name TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE submission_instance (
    submission_instance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_name          VARCHAR(255) NOT NULL
);

CREATE TABLE farmer (
    farmer_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id    BIGINT,
    farmer_name  TEXT NOT NULL,
    farmer_code  VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_farmer_cohort
        FOREIGN KEY (cohort_id)
        REFERENCES cohort (cohort_id)
        ON DELETE SET NULL
);

CREATE TABLE crop (
    crop_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,
    crop_name   VARCHAR(255) NOT NULL,

    CONSTRAINT fk_crop_category
        FOREIGN KEY (category_id)
        REFERENCES category (category_id)
        ON DELETE SET NULL
);

-- =========================
-- Submission and crop data
-- =========================

CREATE TABLE submission (
    submission_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id             BIGINT,
    focal_point_id        BIGINT,
    submission_instance_id BIGINT,
    submission_date       TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_submission_farmer
        FOREIGN KEY (farmer_id)
        REFERENCES farmer (farmer_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_submission_focal_point
        FOREIGN KEY (focal_point_id)
        REFERENCES focal_point (focal_point_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_submission_instance
        FOREIGN KEY (submission_instance_id)
        REFERENCES submission_instance (submission_instance_id)
        ON DELETE SET NULL
);

CREATE TABLE submission_crop (
    submission_crop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id      BIGINT,
    crop_id            BIGINT,
    harvested          BOOLEAN,
    quantity           VARCHAR(255),
    unit               VARCHAR(255),
    usage              TEXT[],          -- raw multiselect from KoBo
    reason_not_sold    TEXT[],          -- raw multiselect from KoBo

    CONSTRAINT fk_submission_crop_submission
        FOREIGN KEY (submission_id)
        REFERENCES submission (submission_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_submission_crop_crop
        FOREIGN KEY (crop_id)
        REFERENCES crop (crop_id)
        ON DELETE SET NULL
);

-- =========================
-- Biochar application + fertilizer
-- =========================

CREATE TABLE biochar_application (
    biochar_application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_crop_id     BIGINT,
    applied                BOOLEAN,
    season                 VARCHAR(255)[],  -- raw list (e.g. "Rainy 2025")
    coverage               TEXT,
    application_method     TEXT[],          -- raw multiselect
    frequency              VARCHAR(255),

    CONSTRAINT fk_biochar_application_submission_crop
        FOREIGN KEY (submission_crop_id)
        REFERENCES submission_crop (submission_crop_id)
        ON DELETE SET NULL
);

CREATE TABLE fertilizer_usage (
    fertilizer_usage_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biochar_application_id BIGINT,
    fertilizer_type       VARCHAR(255)[],   -- raw multiselect
    used_before_biochar   BOOLEAN,
    used_with_biochar     BOOLEAN,

    CONSTRAINT fk_fertilizer_usage_biochar_application
        FOREIGN KEY (biochar_application_id)
        REFERENCES biochar_application (biochar_application_id)
        ON DELETE SET NULL
);

-- =========================
-- Yield impact
-- =========================

CREATE TABLE yield_impact (
    yield_impact_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_crop_id       BIGINT,
    used_on_partial_plot     BOOLEAN,
    observed_difference      BOOLEAN,
    significance_partial_plot VARCHAR(255),
    compared_last_year       BOOLEAN,
    significance_last_year   VARCHAR(255),

    CONSTRAINT fk_yield_impact_submission_crop
        FOREIGN KEY (submission_crop_id)
        REFERENCES submission_crop (submission_crop_id)
        ON DELETE SET NULL
);

-- =========================
-- Farmer feedback (section D–F)
-- =========================

CREATE TABLE farmer_feedback (
    farmer_feedback_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id          BIGINT,
    continue_biochar       BOOLEAN,
    why_not_continue       TEXT,
    biggest_biochar_impact TEXT,
    support_needed         TEXT[],   -- multi-select
    would_purchase         BOOLEAN,
    reason_not_purchase    TEXT[],   -- multi-select
    impact_ratings         JSONB,    -- free JSONB (e.g. soil_fertility, crop_health, water_retention)
    overall_satisfaction   TEXT,
    desired_additional_data TEXT[],  -- multi-select
    excess_produce_solutions TEXT[], -- multi-select

    CONSTRAINT fk_farmer_feedback_submission
        FOREIGN KEY (submission_id)
        REFERENCES submission (submission_id)
        ON DELETE SET NULL
);

-- =========================
-- Many-to-many: biochar ↔ season / method / fertilizer type
-- =========================

CREATE TABLE biochar_season (
    season_id              BIGINT NOT NULL,
    biochar_application_id BIGINT NOT NULL,
    PRIMARY KEY (season_id, biochar_application_id),

    CONSTRAINT fk_biochar_season_season
        FOREIGN KEY (season_id)
        REFERENCES season (season_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_biochar_season_biochar_application
        FOREIGN KEY (biochar_application_id)
        REFERENCES biochar_application (biochar_application_id)
        ON DELETE CASCADE
);

CREATE TABLE biochar_application_method (
    application_method_id  BIGINT NOT NULL,
    biochar_application_id BIGINT NOT NULL,
    PRIMARY KEY (application_method_id, biochar_application_id),

    CONSTRAINT fk_biochar_app_method_method
        FOREIGN KEY (application_method_id)
        REFERENCES application_method (application_method_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_biochar_app_method_application
        FOREIGN KEY (biochar_application_id)
        REFERENCES biochar_application (biochar_application_id)
        ON DELETE CASCADE
);

CREATE TABLE fertilizer_usage_type (
    fertilizer_usage_id BIGINT NOT NULL,
    fertilizer_type_id  BIGINT NOT NULL,
    PRIMARY KEY (fertilizer_usage_id, fertilizer_type_id),

    CONSTRAINT fk_fertilizer_usage_type_usage
        FOREIGN KEY (fertilizer_usage_id)
        REFERENCES fertilizer_usage (fertilizer_usage_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_fertilizer_usage_type_type
        FOREIGN KEY (fertilizer_type_id)
        REFERENCES fertilizer_type (fertilizer_type_id)
        ON DELETE CASCADE
);

-- =========================
-- Many-to-many: crop usage / reason_not_sold
-- =========================

CREATE TABLE submission_crop_usage (
    usage_id          BIGINT NOT NULL,
    submission_crop_id BIGINT NOT NULL,
    PRIMARY KEY (usage_id, submission_crop_id),

    CONSTRAINT fk_submission_crop_usage_usage
        FOREIGN KEY (usage_id)
        REFERENCES usage (usage_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_submission_crop_usage_submission_crop
        FOREIGN KEY (submission_crop_id)
        REFERENCES submission_crop (submission_crop_id)
        ON DELETE CASCADE
);

CREATE TABLE submission_crop_reason_not_sold (
    reason_not_sold_id BIGINT NOT NULL,
    submission_crop_id BIGINT NOT NULL,
    PRIMARY KEY (reason_not_sold_id, submission_crop_id),

    CONSTRAINT fk_submission_crop_rns_reason
        FOREIGN KEY (reason_not_sold_id)
        REFERENCES reason_not_sold (reason_not_sold_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_submission_crop_rns_submission_crop
        FOREIGN KEY (submission_crop_id)
        REFERENCES submission_crop (submission_crop_id)
        ON DELETE CASCADE
);
